INSERT INTO GITHUB.PUBLIC.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, DATE_OF_BIRTH)
VALUES (1, 'John', 'Doe', 'john.doe@example.com', '1990-05-15');

INSERT INTO GITHUB.PUBLIC.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, DATE_OF_BIRTH)
VALUES (2, 'Jane', 'Smith', 'jane.smith@example.org', '1985-12-20');

INSERT INTO GITHUB.PUBLIC.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, DATE_OF_BIRTH)
VALUES (3, 'Peter', 'Jones', 'peter.jones@example.net', '2000-03-10');

INSERT INTO GITHUB.PUBLIC.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL)
VALUES (4, 'Alice', 'Brown', 'alice.brown@sample.com');

INSERT INTO GITHUB.PUBLIC.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH)
VALUES (5, 'Bob', 'Green', '1978-08-01');