name: Snowflake Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - Bola
    paths:
      - "Database/"

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Snowflake CLI with pip
        run: |
          python -m pip install snowflake-cli==3.7.1

      - name: Verify Snowflake CLI Installation
        run: |
          snow --version

      - name: Debug Connection Parameters
        run: |
          echo "Account: ${{ env.SNOWFLAKE_ACCOUNT }}"
          echo "User: ${{ env.SNOWFLAKE_USER }}"
          echo "Role: ${{ env.SNOWFLAKE_ROLE }}"
          echo "Warehouse: ${{ env.SNOWFLAKE_WAREHOUSE }}"
          echo "Database: ${{ env.SNOWFLAKE_DATABASE }}"
          echo "Schema: ${{ env.SNOWFLAKE_SCHEMA }}"

      - name: Test Snowflake Connection
        run: |
          mkdir -p ~/.snowflake
          echo '[connections.temp_connection]' > ~/.snowflake/config.toml
          echo 'account = "${{ env.SNOWFLAKE_ACCOUNT }}"' >> ~/.snowflake/config.toml
          echo 'user = "${{ env.SNOWFLAKE_USER }}"' >> ~/.snowflake/config.toml
          echo 'password = "${{ env.SNOWFLAKE_PASSWORD }}"' >> ~/.snowflake/config.toml
          echo 'role = "${{ env.SNOWFLAKE_ROLE }}"' >> ~/.snowflake/config.toml
          echo 'warehouse = "${{ env.SNOWFLAKE_WAREHOUSE }}"' >> ~/.snowflake/config.toml
          echo 'database = "${{ env.SNOWFLAKE_DATABASE }}"' >> ~/.snowflake/config.toml
          echo 'schema = "${{ env.SNOWFLAKE_SCHEMA }}"' >> ~/.snowflake/config.toml
          echo 'authenticator = "password"' >> ~/.snowflake/config.toml
          chmod 0600 ~/.snowflake/config.toml
          echo "Config file content:"
          sed 's/password = .*/password = [REDACTED]/' ~/.snowflake/config.toml
          echo "SELECT CURRENT_VERSION();" > test.sql
          snow sql -f test.sql --connection temp_connection 2>&1 | tee connection_output.log
          if [ $? -ne 0 ]; then
            echo "Connection test failed with error code $?"
            cat connection_output.log
            cat test.sql
            exit 1
          fi
        env:
          SNOWSQL_PWD: ${{ env.SNOWFLAKE_PASSWORD }}


      - name: List SQL Files
        run: |
          ls -l Database/*.sql || echo "No SQL files found"

      - name: Execute Snowflake SQL Files
        run: |
          if ls Database/*.sql >/dev/null 2>&1; then
            for file in Database/*.sql; do
              echo "Executing $file..."
              snow sql -f "$file" \
                --connection temp_connection \
                -o variable_substitution=true 2>&1 | tee output.log
              if [ $? -ne 0 ]; then
                echo "Error executing $file"
                cat output.log
                exit 1
              fi
            done
          else
            echo "No SQL files found in Database/ folder."
          fi
        env:
          SNOWSQL_PWD: ${{ env.SNOWFLAKE_PASSWORD }}
