name: test-compare-versions-pip-and-pipx

on:
  workflow_dispatch:
  push:
    branches:
      - Bola
    paths:
      - "Database/"

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
    # Step 1: Install Snowflake CLI
    name: Install Snowflake CLI with pip
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Snowflake CLI with pip
        run: |
          python -m pip install snowflake-cli

      - name: Store snow version
        shell: bash
        run: |
          snow --version >> version_output.txt
          echo "snow_version_pip=$(cat version_output.txt)" >> $GITHUB_ENV
    # Step 4: Configure Snowflake CLI
      - name: Configure Snowflake CLI
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
