name: Execute Snowflake SQL Files

on:
  workflow_dispatch:
  push:
    branches:
      - Bola
    paths:
      - 'Database/'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install Snowflake CLI
      - name: Install Snowflake CLI
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-cli-labs==2.8.1
          # Ensure the pip-installed binaries are in PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          # Verify installation
          which snowflake
          snowflake --version

      # Step 4: Configure and Run Snowflake CLI
      - name: Configure Snowflake CLI
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Running Snowflake CLI"
          # Debug: Print PATH and check snowflake command
          echo "PATH: $PATH"
          which snowflake
          snowflake --version
          # Test Snowflake connection
          echo "Testing Snowflake connection"
          snowflake sql -c default -q "SELECT CURRENT_VERSION();" \
            --account $SNOWFLAKE_ACCOUNT \
            --user $SNOWFLAKE_USER \
            --password $SNOWFLAKE_PASSWORD \
            --role $SNOWFLAKE_ROLE \
            --warehouse $SNOWFLAKE_WAREHOUSE \
            --database $SNOWFLAKE_DATABASE \
            --schema $SNOWFLAKE_SCHEMA || { echo "Snowflake connection failed"; exit 1; }
          # Check if SQL files exist
          echo "Listing SQL files in $GITHUB_WORKSPACE/Database/"
          ls -l $GITHUB_WORKSPACE/Database/*.sql || { echo "No SQL files found"; exit 1; }
          # Execute SQL files with error handling
          for file in $GITHUB_WORKSPACE/Database/*.sql; do
            if [ -f "$file" ]; then
              echo "Executing SQL file: $file"
              snowflake sql -c default -f "$file" \
                --account $SNOWFLAKE_ACCOUNT \
                --user $SNOWFLAKE_USER \
                --password $SNOWFLAKE_PASSWORD \
                --role $SNOWFLAKE_ROLE \
                --warehouse $SNOWFLAKE_WAREHOUSE \
                --database $SNOWFLAKE_DATABASE \
                --schema $SNOWFLAKE_SCHEMA || { echo "Error executing $file"; exit 1; }
            else
              echo "No SQL files found in $GITHUB_WORKSPACE/Database/"
              exit 1
            fi
          done
