name: Working

on:
  workflow_dispatch:
  push:
    branches:
      - Bola
    paths:
      - 'Database/'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - uses: actions/checkout@v4

      - name: Install SnowSQL
        run: |
          set -e
          echo "Downloading SnowSQL installer..."
          curl -f -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.0-linux_x86_64.bash || { echo "Failed to download SnowSQL installer"; exit 1; }
          echo "Installing SnowSQL..."
          SNOWSQL_DEST=/home/runner/bin bash snowsql-1.3.0-linux_x86_64.bash || { echo "SnowSQL installation failed"; exit 1; }
          echo "Verifying SnowSQL installation..."
          /home/runner/bin/snowsql --version || { echo "SnowSQL not installed correctly"; exit 1; }
        shell: bash

      - name: Execute SQL files
        run: |
          set -e
          for file in $(ls Database/*.sql | sort); do
            echo "Executing $file"
            /home/runner/bin/snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER --password $SNOWFLAKE_PASSWORD -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -s $SNOWFLAKE_SCHEMA -f $file -o friendly=false
          done
        shell: bash
